repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        always_run: true
        pass_filenames: false
      - id: test
        name: test
        entry: make test
        language: system
        always_run: true
        pass_filenames: false
